---
- name: "upgrade packages."
  become: true
  apk:
    upgrade: "yes"

- name: "install dependencies."
  become: true
  apk:
    name: ["nodejs", "npm"]
    update_cache: yes
    state: present

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present