---
- name: Create backend dir
  file:
    path: /opt/app
    state: directory

- name: "unzip backend."
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /opt/app

- name: "Start backend"
  become: true
  command: |
    cd /opt/app
    npm install
    pm2 stop default
    pm2 start npm -- start
